plugins:
  - babel
  - jest
env:
  node: true
  jest: true
parser: babel-eslint
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
rules:
  comma-dangle:
    - error
    - always
  no-console: 0